# Generated by Django 3.0.7 on 2021-11-26 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_actividad', models.CharField(choices=[('', '----------'), ('CE', 'Carnes y embutidos'), ('FV', 'Frutas y verduras'), ('PC', 'Pescados y conservas'), ('OA', 'Otros porudctos de alimentacion'), ('BA', 'Bebidas y alcoholes'), ('CP', 'Calzado y piel'), ('T', 'Textiles'), ('C', 'Corcho'), ('CM', 'Construcción y mobiliario'), ('SI', 'Suministros industriales'), ('PQ', 'Productos químicos y básicos'), ('SC', 'Servicios de consultoría'), ('SM', 'Servicios de montaje/mantenimiento/técnico'), ('SGR', 'Servicios de gestión de residuos'), ('SIE', 'Servicios de ingeniería/energía/renovables y economía circular'), ('TIC', 'Servicios TIC'), ('OTHER', 'Otros')], max_length=5)),
                ('otro_producto_servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('cif', models.CharField(max_length=10)),
                ('pyme', models.IntegerField(choices=[(0, 'Si'), (1, 'No')])),
                ('direccion_fiscal', models.CharField(max_length=250)),
                ('phone_empresa', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='EL numero de telefono debe ser en el formato de: +9999999999.', regex='^\\+?1?\\d{9,15}$')])),
                ('email_empresa', models.EmailField(max_length=254)),
                ('nombre_persona_contacto', models.CharField(help_text='Nombre de Persona de contacto.', max_length=150)),
                ('cargo_persona_contacto', models.CharField(help_text='Cargo de persona de contacto.', max_length=150)),
                ('email_persona_contacto', models.EmailField(help_text='Email de la persona de contacto.', max_length=254)),
                ('phone_persona_contacto', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='EL numero de telefono debe ser en el formato de: +9999999999.', regex='^\\+?1?\\d{9,15}$')])),
                ('ceo_nombre', models.CharField(blank=True, help_text='Nombre de CEO or Gerente.', max_length=150, null=True)),
                ('ceo_email', models.EmailField(blank=True, help_text='Email de CEO or Gerente.', max_length=254, null=True)),
                ('ceo_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='EL numero de telefono debe ser en el formato de: +9999999999.', regex='^\\+?1?\\d{9,15}$')])),
                ('web', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('otro_redes', models.URLField(blank=True, null=True)),
                ('empleados_fijos', models.CharField(choices=[('CC', '0-5'), ('SD', '6-10'), ('OV', '11-20'), ('VT', '21-30'), ('TC', '31-50'), ('CD', '51-250'), ('GD', '>250')], max_length=2)),
                ('empleados_eventuales', models.CharField(choices=[('CCE', '0-5'), ('SDE', '6-10'), ('OVE', '11-20'), ('VTE', '21-30'), ('TCE', '31-50'), ('CDE', '51-250'), ('GDE', '>250')], max_length=3)),
                ('volumen_facturacion', models.CharField(choices=[('MM', '<100.000 euros'), ('MQ', '100.000-500.000 euros'), ('QMM', '500.001-1.000.000 euros'), ('MQM', '1.000.000-5.000.000 euros'), ('QQD', '5.000.001-10.000.000 euros'), ('GTM', '>10.000.000 euros')], max_length=3)),
                ('export_frecuencia', models.CharField(choices=[('EH', 'Exportadora habitual'), ('EO', 'Exportadora ocasional'), ('EP', 'Empresa con potencial exportador')], max_length=2)),
                ('export_relativa', models.PositiveSmallIntegerField()),
                ('export_vol', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taric', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_servicios', to='empresa.Empresa')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_actividad',
            field=models.ManyToManyField(related_name='direccion', to='empresa.Municipio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='export_destino',
            field=models.ManyToManyField(to='empresa.Countries'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cif'], name='empresa_idx'),
        ),
    ]
