# Generated by Django 3.0.7 on 2021-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='alpha',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
