# Generated by Django 3.0.7 on 2021-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
