# Generated by Django 3.0.7 on 2021-10-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='alpha',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1, null=True),
        ),
    ]
