# Generated by Django 3.0.7 on 2021-11-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='slug',
        ),
    ]
