# Generated by Django 3.0.7 on 2021-11-30 14:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_remove_empresa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='export_destino',
        ),
        migrations.AddField(
            model_name='empresa',
            name='export_destino',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
