# Generated by Django 3.0.7 on 2021-10-21 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20211019_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='alpha',
        ),
    ]
