# Generated by Django 3.0.7 on 2021-11-30 15:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_delete_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='export_destino',
            field=django_countries.fields.CountryField(default=1, max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
