# Generated by Django 3.0.7 on 2021-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_auto_20211130_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_email', models.EmailField(max_length=254)),
                ('request_f_name', models.CharField(max_length=250)),
                ('request_l_name', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(0, 'Por confirmar'), (1, 'Enviada')], default=0)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='export_relativa',
            field=models.CharField(choices=[('MM', '<100.000 euros'), ('MQ', '100.000-500.000 euros'), ('QMM', '500.001-1.000.000 euros'), ('MQM', '1.000.000-5.000.000 euros'), ('QQD', '5.000.001-10.000.000 euros'), ('GTM', '>10.000.000 euros')], max_length=3),
        ),
    ]
