# Generated by Django 3.0.7 on 2021-12-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20211206_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='empresas',
            field=models.ManyToManyField(to='empresa.Empresa'),
        ),
    ]
